/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package XML_Parse_Manager;

import java.io.File;
import javax.swing.JDialog;
import javax.swing.JFileChooser;

/**
 *
 * @author atorralba.ext
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
 
    
    
    public MainFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VSelec = new javax.swing.JFrame();
        VArchivo = new javax.swing.JFileChooser();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        TxtRuta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtXML = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        LProceso = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LPaso = new javax.swing.JLabel();

        VSelec.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        VSelec.setPreferredSize(new java.awt.Dimension(600, 600));
        VSelec.setResizable(false);
        VSelec.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                VSelecFocusLost(evt);
            }
        });

        VArchivo.setCurrentDirectory(new java.io.File("C:\\"));
            VArchivo.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    VArchivoActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout VSelecLayout = new javax.swing.GroupLayout(VSelec.getContentPane());
            VSelec.getContentPane().setLayout(VSelecLayout);
            VSelecLayout.setHorizontalGroup(
                VSelecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(VArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            );
            VSelecLayout.setVerticalGroup(
                VSelecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(VArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            );

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            jButton1.setText("Cargar XML");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            TxtXML.setColumns(20);
            TxtXML.setRows(5);
            jScrollPane1.setViewportView(TxtXML);

            jLabel1.setText("Proceso : ");

            LProceso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

            jLabel3.setText("Paso : ");

            LPaso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator1)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(TxtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addGap(178, 178, 178)
                    .addComponent(jButton1)
                    .addGap(158, 158, 158)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(LProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(40, 40, 40)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(LPaso, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addGap(48, 48, 48))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(TxtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addComponent(LPaso, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE))
                        .addComponent(LProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap())
            );

            pack();
            setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        JDialog a = new JDialog();
        a.add(VArchivo);
        
        if(VArchivo.showOpenDialog(a) == JFileChooser.APPROVE_OPTION)
        {
            File archivo = VArchivo.getSelectedFile();
        
            archivo.getAbsolutePath();
            PruebaXMLtoArray.ruta = archivo.toString();
            TxtRuta.setText(archivo.toString());
            
            PruebaXMLtoArray lanza = new PruebaXMLtoArray();
            
            
            TxtXML.setText(PruebaXMLtoArray.XML);
            LPaso.setText(PruebaXMLtoArray.paso);
            LProceso.setText(PruebaXMLtoArray.proceso);
            
        }
        
        
        
        
//        VSelec.setVisible(true);
        VSelec.setLocation(this.getLocation());
        VSelec.setSize(800,400);
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void VArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VArchivoActionPerformed

    private void VSelecFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_VSelecFocusLost
        
    }//GEN-LAST:event_VSelecFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    public static void  añade()
    {
        TxtXML.append(PruebaXMLtoArray.XML);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LPaso;
    private javax.swing.JLabel LProceso;
    private javax.swing.JTextField TxtRuta;
    public static javax.swing.JTextArea TxtXML;
    private javax.swing.JFileChooser VArchivo;
    private javax.swing.JFrame VSelec;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
